# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gpios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgpio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vgpio',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
