# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
