# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_auto_20171122_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
