# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_auto_20171123_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='id',
            field=models.UUIDField(default=uuid.UUID('34404d6e-c6f0-4750-9ce0-91aef5e1188f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
