# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0006_auto_20171124_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ('tipo',)},
        ),
    ]
